version: "3.9"

services:
  budget-agent:
    build: .
    image: budget-agent:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s